### ISSUE TITLE
some 7z crash droidsound-e

### ISSUE THREAD

**Issue by dominater01** [droidmjt/Droidsound#159]
when I try scanning sg-1000.7z it crashes the application everything else scans just fine except game boy advance they should have worked like they used to I didn't change them

I have the latest beta just got it today

crash log Sez 

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.sddb.droidsound.OPEN_DONE flg=0x10 } in com.droidmjt.droidsounde.PlayerActivity$5@4141b0a8
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:727)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1565)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1514)
	at com.droidmjt.droidsounde.database.SongDatabase.updateplistCount(SongDatabase.java:2451)
	at com.droidmjt.droidsounde.PlayerActivity$5.onReceive(PlayerActivity.java:1137)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:758)
	... 10 more
============================
Droidsound-E version: 34
Time: Tue Apr 14 00:42:21 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: asus/WW_epad/K00F:4.2.2/JDQ39/WW_user_4.2.2_3.11.0.100_20141027:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 
Lang: English
Locale: en_US
InternalSD free space: 1172492288
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment]
thanks for using droidsounde_crashlog, logcat log is so yesterday :) i'll check this

**Comment by droidmjt** [comment]
could you resend those files, i lost them, thanks

**Comment by droidmjt** [comment]
i can see the problem, i'll fix it.

**Comment by droidmjt** [comment]
sc1000 thing fixed

**Comment by dominater01** [comment]
my gameboy advance pack gives me this error

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.ExceptionInInitializerError
	at com.droidmjt.droidsounde.plugins.MP3Plugin.load(MP3Plugin.java:258)
	at com.droidmjt.droidsounde.plugins.MP3Plugin.loadInfo(MP3Plugin.java:311)
	at com.droidmjt.droidsounde.FileIdentifier.tryLoad(FileIdentifier.java:229)
	at com.droidmjt.droidsounde.FileIdentifier.identify(FileIdentifier.java:308)
	at com.droidmjt.droidsounde.database.SongDatabase.scanZip(SongDatabase.java:485)
	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:872)
	at com.droidmjt.droidsounde.database.SongDatabase.doScan(SongDatabase.java:1266)
	at com.droidmjt.droidsounde.database.SongDatabase.access$300(SongDatabase.java:91)
	at com.droidmjt.droidsounde.database.SongDatabase$MyHandler.handleMessage(SongDatabase.java:245)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at com.droidmjt.droidsounde.database.SongDatabase.run(SongDatabase.java:280)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_alloc(linker.cpp:287): too many libraries when loading "libtags.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:371)
	at java.lang.System.loadLibrary(System.java:535)
	at com.un4seen.bass.TAGS.<clinit>(TAGS.java:14)
	... 13 more
============================
Droidsound-E version: 34
Time: Tue Apr 14 11:19:46 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: asus/WW_epad/K00F:4.2.2/JDQ39/WW_user_4.2.2_3.11.0.100_20141027:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 
Lang: English
Locale: en_US
InternalSD free space: 1104719872
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment]
what file extensions you have in your GBA pack? could you send me one of those files?

**Comment by dominater01** [comment]
they are in .minigsf

I got them here http://www.zophar.net/music/gsf/

**Comment by droidmjt** [comment]
I'll check it. I wonder what mp3plugin has to do with minigsf.

**Comment by droidmjt** [comment]
I just tried with one of those 7z files and worked fine. This is not related to minigsf but something else. I'll investigate.

**Comment by droidmjt** [comment]
new binary upped, try it, at least the sc1000 bug should be gone

**Comment by dominater01** [comment]
I'll try it out 

also here's the pack to my gbagba music 

https://www.dropbox.com/s/6r200ov42dzug2b/Gameboy%20Advance.7z?dl=0

**Comment by droidmjt** [comment]
thanks i'll test those

**Comment by droidmjt** [comment]
That gba package has mp3, mod etc etc files, thats why there is this mp3plugin in the crashlog. 

I couldn't reproduce the crash. It scanned the archive just fine.

**Comment by dominater01** [comment]
I don't know what I can do about it then it's the only pack I got that doesn't work now

**Comment by droidmjt** [comment]
try so that you remove the single mp3 file from it and rescan it. I can do more testing today

**Comment by dominater01** [comment]
im not seeing a mp3 file anywhere in the pack?
