### ISSUE TITLE
Crash when adding song to favorites

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#160]
This one did make a crashlog

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NumberFormatException: Invalid int: "Think & Feel, Square Enix"
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parse(Integer.java:410)
	at java.lang.Integer.parseInt(Integer.java:367)
	at java.lang.Integer.parseInt(Integer.java:334)
	at com.droidmjt.droidsounde.Playlist.add(Playlist.java:552)
	at com.droidmjt.droidsounde.PlayerActivity$31.onClick(PlayerActivity.java:3148)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
============================
Droidsound-E version: 34
Time: Wed Apr 15 08:22:05 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: REMOVED
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 748392448
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment]
excellent, how i can reproduce this problem?

**Comment by Level99OCR** [comment]
This one occured using 2SF format.  Haven't tried favoriting anything else.

**Comment by droidmjt** [comment]
fixed

**Comment by droidmjt** [comment]
new binary in dropbox.com link

**Comment by Level99OCR** [comment]
Tested fixed on SGS3 4.4 stock.
