### ISSUE TITLE
DS FC (possibly mp3-related) - Stock 5.0.2 Lollipop Device

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#163]
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.ArrayIndexOutOfBoundsException: length=65536; regionStart=65536; regionLength=65536
	at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:197)
	at com.droidmjt.droidsounde.file.FileSource.storeData(FileSource.java:167)
	at com.droidmjt.droidsounde.file.FileSource.getData(FileSource.java:298)
	at com.droidmjt.droidsounde.file.FileSource.getFile(FileSource.java:340)
	at com.droidmjt.droidsounde.plugins.MP3Plugin.load(MP3Plugin.java:209)
	at com.droidmjt.droidsounde.plugins.MP3Plugin.loadInfo(MP3Plugin.java:284)
	at com.droidmjt.droidsounde.FileIdentifier.tryLoad(FileIdentifier.java:229)
	at com.droidmjt.droidsounde.FileIdentifier.identify(FileIdentifier.java:308)
	at com.droidmjt.droidsounde.database.SongDatabase.scanZip(SongDatabase.java:488)
	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:875)
	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:969)
	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:969)
	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:983)
	at com.droidmjt.droidsounde.database.SongDatabase.doScan(SongDatabase.java:1269)
	at com.droidmjt.droidsounde.database.SongDatabase.access$300(SongDatabase.java:92)
	at com.droidmjt.droidsounde.database.SongDatabase$MyHandler.handleMessage(SongDatabase.java:248)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at com.droidmjt.droidsounde.database.SongDatabase.run(SongDatabase.java:283)
	at java.lang.Thread.run(Thread.java:818)
============================
Droidsound-E version: 34
Time: Fri Apr 24 08:52:18 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: lge/w7_tmo_us/w7:5.0.2/LRX22G/150651744a25e:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 1407373312
InternalSD path: /storage/emulated/0

Was scanning some joint vgm/mp3 zips for Sega Genesis/Sega CD music.  Switched to a different device for a little while due to softbrick, I have not made any modifications besides adding root (and all of my devices basically have root).

I have a gut feeling you won't be able to replicate this, though.

This was a clean install using the binary you uploaded to dropbox yesterday, stock options (FileCache set to the current 32mb Default).

If you're making major changes at this time, this can probably take a backseat.  I'm going to try the FileCache size increase thing.

**Comment by droidmjt** [comment]
dont worry about this, i know what causes this, this was a temporary hack, i'll upload new build within next 48 hours

**Comment by droidmjt** [comment]
new beta in dropbox, go go go, get ready to experience more horror :)

**Comment by Level99OCR** [comment]
OH NO, THE HORRORRRRRRRRRRRRRRRR!

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
	at com.droidmjt.droidsounde.plugins.VGMPlugin.loadInfo(VGMPlugin.java:90)
	at com.droidmjt.droidsounde.FileIdentifier.tryLoad(FileIdentifier.java:229)
	at com.droidmjt.droidsounde.FileIdentifier.identify(FileIdentifier.java:308)
	at com.droidmjt.droidsounde.database.SongDatabase.scanZip(SongDatabase.java:488)
	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:875)
	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:969)
	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:983)
	at com.droidmjt.droidsounde.database.SongDatabase.doScan(SongDatabase.java:1269)
	at com.droidmjt.droidsounde.database.SongDatabase.access$300(SongDatabase.java:92)
	at com.droidmjt.droidsounde.database.SongDatabase$MyHandler.handleMessage(SongDatabase.java:248)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at com.droidmjt.droidsounde.database.SongDatabase.run(SongDatabase.java:283)
	at java.lang.Thread.run(Thread.java:818)
============================
Droidsound-E version: 34
Droidsound-E Build: 2
Time: Mon Apr 27 13:05:05 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: samsung/d2uc/d2att:4.4.2/KOT49H/I747UCUFNE4:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 8644153344
InternalSD path: /storage/emulated/0

**Comment by Level99OCR** [comment]
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
	at com.droidmjt.droidsounde.plugins.NDSPlugin.loadInfo(NDSPlugin.java:100)
	at com.droidmjt.droidsounde.FileIdentifier.tryLoad(FileIdentifier.java:229)
	at com.droidmjt.droidsounde.FileIdentifier.identify(FileIdentifier.java:308)
	at com.droidmjt.droidsounde.database.SongDatabase.scanZip(SongDatabase.java:488)
	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:875)
	at com.droidmjt.droidsounde.database.SongDatabase.doScanDir(SongDatabase.java:1067)
	at com.droidmjt.droidsounde.database.SongDatabase.access$400(SongDatabase.java:92)
	at com.droidmjt.droidsounde.database.SongDatabase$MyHandler.handleMessage(SongDatabase.java:253)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at com.droidmjt.droidsounde.database.SongDatabase.run(SongDatabase.java:283)
	at java.lang.Thread.run(Thread.java:818)
============================
Droidsound-E version: 34
Droidsound-E Build: 2
Time: Mon Apr 27 15:18:09 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: samsung/d2uc/d2att:4.4.2/KOT49H/I747UCUFNE4:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 8625668096
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment]
odd, i try to reproduce this problem

**Comment by droidmjt** [comment]
i just uploaded new beta binary, it fixes few other problems

**Comment by droidmjt** [comment]
found more bugs, i'll fix them

**Comment by Level99OCR** [comment]
![worlds_greatest_software_engineer_mug-rf389ea84764f4edcbfaa014d526bedc9_x7jgr_8byvr_324](https://cloud.githubusercontent.com/assets/6171738/7369286/bdb84808-ed7e-11e4-8232-9b36247c47f2.jpg)

**Comment by droidmjt** [comment]
new binary in dropbox, hopefully less horror :)

**Comment by Level99OCR** [comment]
This crash happens every time I try to add /storage/external_Sd/VGM/ filebrowser after a clean install:

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException
	at java.io.File.fixSlashes(File.java:185)
	at java.io.File.<init>(File.java:134)
	at com.droidmjt.droidsounde.database.SongDatabase.doScan(SongDatabase.java:1155)
	at com.droidmjt.droidsounde.database.SongDatabase.access$300(SongDatabase.java:92)
	at com.droidmjt.droidsounde.database.SongDatabase$MyHandler.handleMessage(SongDatabase.java:248)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at com.droidmjt.droidsounde.database.SongDatabase.run(SongDatabase.java:283)
	at java.lang.Thread.run(Thread.java:841)
============================
Droidsound-E version: 34
Droidsound-E Build: 2
Time: Thu Apr 30 09:51:18 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: lge/geehrc_kt_kr/geehrc:4.4.2/KOT49I.F180K30b/F180K30b.1399632318:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 
Lang: English
Locale: en_US
InternalSD free space: 11634016256
InternalSD path: /storage/emulated/0


This crash happens when scanning my various Genesis archives:
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.droidmjt.droidsounde/com.droidmjt.droidsounde.PlayerActivity}: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: SELECT TITLE FROM PLAYLISTS WHERE TITLE=?
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2202)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2252)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3757)
	at android.app.ActivityThread.access$900(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: SELECT TITLE FROM PLAYLISTS WHERE TITLE=?
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:892)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:503)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1415)
	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1262)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1133)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1339)
	at com.droidmjt.droidsounde.database.SongDatabase.createPlaylist(SongDatabase.java:2677)
	at com.droidmjt.droidsounde.PlayerActivity.checkPlaylists(PlayerActivity.java:945)
	at com.droidmjt.droidsounde.PlayerActivity.onCreate(PlayerActivity.java:1675)
	at android.app.Activity.performCreate(Activity.java:5275)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166)
	... 12 more
============================
Droidsound-E version: 34
Droidsound-E Build: 2
Time: Thu Apr 30 10:17:21 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: lge/geehrc_kt_kr/geehrc:4.4.2/KOT49I.F180K30b/F180K30b.1399632318:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 
Lang: English
Locale: en_US
InternalSD free space: 11602669568
InternalSD path: /storage/emulated/0

This crash happens when scanning my various DS archives:

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.droidmjt.droidsounde/com.droidmjt.droidsounde.PlayerActivity}: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: SELECT TITLE FROM PLAYLISTS WHERE TITLE=?
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2202)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2252)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3757)
	at android.app.ActivityThread.access$900(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: SELECT TITLE FROM PLAYLISTS WHERE TITLE=?
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:892)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:503)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1415)
	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1262)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1133)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1339)
	at com.droidmjt.droidsounde.database.SongDatabase.createPlaylist(SongDatabase.java:2677)
	at com.droidmjt.droidsounde.PlayerActivity.checkPlaylists(PlayerActivity.java:945)
	at com.droidmjt.droidsounde.PlayerActivity.onCreate(PlayerActivity.java:1675)
	at android.app.Activity.performCreate(Activity.java:5275)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166)
	... 12 more
============================
Droidsound-E version: 34
Droidsound-E Build: 2
Time: Thu Apr 30 11:26:56 EDT 2015
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: lge/geehrc_kt_kr/geehrc:4.4.2/KOT49I.F180K30b/F180K30b.1399632318:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 
Lang: English
Locale: en_US
InternalSD free space: 11606560768
InternalSD path: /storage/emulated/0

**Comment by Level99OCR** [comment]
Definitely seems less horror-able though, what was successfully scanned so far has played flawlessly as far as I can tell.

**Comment by droidmjt** [comment]
>>at com.droidmjt.droidsounde.database.SongDatabase.doScan(SongDatabase.java:1155)

that one caused lots of problems, but it's fixed, unfortunately i forgot to upload the binary that has the fix :)

i'll upload it now

**Comment by droidmjt** [comment]
actually, i'm gonna fix couple of easy bugs and then upload it

**Comment by droidmjt** [comment]
new binary available

**Comment by droidmjt** [comment]
unbelieveable, that same shit is still there

**Comment by droidmjt** [comment]
new binary uploaded, that crash is gone now

**Comment by Level99OCR** [comment]
Okay, I did only just now grab the latest binary.  Running it now, might be the new rom I put on there or the fix might have done it but the scan is moving much slower than in previous versions.  Not a huge deal at all, it did not have a start-crash though, so at least part of the bug has been fixed.  Will report back once the scans are done about any other crashes, looks like it'll be tomorrow at the rate the scan is going but I'll give feedback ASAP! Thanks so much.

**Comment by droidmjt** [comment]
the latest beta binary is just 7 minutes old, all right, laters

**Comment by Level99OCR** [comment]
It was the kernel in the rom I was using that was super slow, flash a different one and its back up to normal speed.  Still getting the SQL database lock on occasion as far as I can tell, but the initial crash for fixslashes is fixed.

**Comment by droidmjt** [comment]
which kernel you have now?

**Comment by Level99OCR** [comment]
Stock CM 12.1, the one i was using before was Blisspop 5.0.  It's the only one I've seen that has the slowdown so I can only assume its got to do with the props the kernel uses or the toolchain that was used to compile it.  Stock GS3 runs fine, and CM12.1 seems to run fine as well.

After doing a clean sweep, I've get to get a FC.  Its running against the Genesis stuff now, and Genesis/DS was what caused the SQL locks before.  So we'll see if it happens now.

**Comment by droidmjt** [comment]
do you know if there is CM12.1 for Samsung Galaxy S3 4G GT-i9305 (International) model? I have now spare phone so i can also test with that :)

**Comment by Level99OCR** [comment]
http://forum.xda-developers.com/galaxy-s3/development-i9305 Look for threads that list I9305 in them.  Specifically, here is your thread for CM 12.1 for I9305:
http://forum.xda-developers.com/galaxy-s3/development-i9305/rom-t3066156

And here's a good general starting thread for the stuff you'll need to do to get a custom ROM on your device (Rooting, Unlocking Bootloader, Flashing Custom Recovery, Flashing Rom)
http://forum.xda-developers.com/galaxy-s3/general/samsung-galaxy-s3-sticky-roll-thread-t2344125

I've been doing this kind of stuff for half a decade now so if you have any questions or issues getting the custom stuff running, shoot me an email and we can deal with it in a sidebar thread.

**Comment by droidmjt** [comment]
all right, i found some CM12.1 already
cm-12.1-20150430-UNOFFICIAL-i9305.zip i suppose that is correct

**Comment by Level99OCR** [comment]
Yeah, that should be the latest unofficial.  Some other listed versions use different sources, such as actual source blobs from the Samsung Open Source kernels, but most of the CM-based stuff is all AOSP with minimal or no proprietary stuff.  If you're flashing CM12.1, you'll need a GAPPS for 5.1 (Google is fine with custom roms based on AOSP but it requires any google-based apps or code to be removed and installed separately, like Google Play Services, Play Store, Gmail, Youtube, etc.).  So once you get the phone rooted and bootloader unlocked with a custom recovery, you can flash CM12.1 followed by the GAPPS.  Then you should be good to go for testing on the most popular non-stock ROM flavor.

**Comment by droidmjt** [comment]
sounds good, let's see if i can get my sgs3 destroyed :)

**Comment by Level99OCR** [comment]
Oh right, before you install anything new, make sure to get ODIN and the stock rom you have now. And make a NANDROID (recovery-based) backup so you can restore if/when stuff goes bad.  You ESPECIALLY need to make backups of your EFS partitions.  The SGS3 is hard to kill, but not impossible.  I'm speaking from experience :p

**Comment by droidmjt** [comment]
bugger, thanks for the tip, i'll try to get those :)

**Comment by Level99OCR** [comment]
As an aside, it would probably be best to add a .nomedia file to /droidsound/.  This will prevent Android's built in media scanner from adding any images or sound files to the media library automatically.  As far as I can tell, ringtones that are manually selected bypass this so the system can use them without it being in the media library.  Same thing with the /DSEMusic/ directory.  /dsroot/ already has one.  It may or may not be a contributing factor to lock-based crashes if it's having a contention with the native media scanner.

**Comment by droidmjt** [comment]
ohh so thats what the .nomedia file is for, i removed the code that adds it :( I'll put it back

**Comment by droidmjt** [comment]
nevermind, i didn't remove it, i thought i removed it since i didnt see it in droidsound folder, i should have read your msg carefully

**Comment by Level99OCR** [comment]
No worries. Yeah, it was originally in /dsroot/ to keep the media scanner from grabbing any of the files from in there and allocating them.  .nomedia tells the scanner to ignore all files in that folder and any subfolders.  I put it in my folders as a test, so far no crashes but its still got a good bit of scanning left to do.

**Comment by droidmjt** [comment]
installed CM12.1, its nice, works very well and the installation was easier than I expected

**Comment by Level99OCR** [comment]
Okay, I'm going to tentatively close this because I've tested on a Stock KK, CM 12.1, and Stock Lollipop and the .nomedia plus your other recent change seems to have averted the database locking on most devices.  I have one device that's still getting it but its 4.0, low end, and generally a piece of crap.  I'll continue testing though.  Thanks for taking care of this, definitely include the .nomedia in all droidsound root directories though (DSEMusic, droidsound, and dsroot) in future releases.

**Comment by Level99OCR** [comment]
No recurrence of this issue lately.  Also I have confirmed that "slow scan" I was experiencing was ROM-specific (official CM12 nightlies for one of my devices has a botch somewhere, the unofficial CM12.1 for it work just fine).

**Comment by droidmjt** [comment]
Thats great. I also did some file scanning tests with CM12.1 using my custom fileset and it worked fine.
