### ISSUE TITLE
.ydsp extension not detected

### ISSUE THREAD

**Issue by 47iscool** [droidmjt/Droidsound#245]
The WWE GameCube games use this format BTW.

**Comment by droidmjt** [comment]
fixed

**Comment by 47iscool** [comment]
Thanks again mjt.

**Comment by 47iscool** [comment]
Is it on gp or just here?  

It says last update was two days ago.

**Comment by droidmjt** [comment]
not uploaded yet, i need to do another fix

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/kkzac6e9cof45nm/droidsounde16647_25.apk?dl=0

**Comment by 47iscool** [comment]
"Droidsound has unfortunately stopped working"

I have even deleted the cache and folders and it still crashes.

**Comment by droidmjt** [comment]
send me the crashlog, should be in droidsound or droidsound/crashlogs folder

**Comment by 47iscool** [comment]
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.droidmjt.droidsounde/com.droidmjt.droidsounde.PlayerActivity}: java.util.ConcurrentModificationException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2214)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
	at android.app.ActivityThread.access$600(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:152)
	at android.app.ActivityThread.main(ActivityThread.java:5136)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.droidmjt.droidsounde.PlayerActivity$FolderWalker.getexternalSDPaths(PlayerActivity.java:1496)
	at com.droidmjt.droidsounde.PlayerActivity.onCreate(PlayerActivity.java:2691)
	at android.app.Activity.performCreate(Activity.java:5133)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
	... 11 more
============================
Droidsound-E version: 39
Droidsound-E build: 16
Time: Mon Jan 04 07:42:17 EST 2016
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: zte/P821A17/demi:4.3/JLS36C/20140529.033010.24400:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 1858535424
InternalSD path: /storage/sdcard0

**Comment by 47iscool** [comment]
pastebin link
http://pastebin.com/2jTi7teU

**Comment by 47iscool** [comment]
I'm not sure why apps think it's only dual core. 

It's a ZTE Whirl 2, quad-core 1.2 Ghz with about 402 MB of RAM.

**Comment by droidmjt** [comment]
thanks for the crashlog, i can see the problem, will be fixed very soon, new binary will become available in next 6 hours

**Comment by 47iscool** [comment]
Thanks a lot.

**Comment by droidmjt** [comment]
i'll fix the #246 and upload it then

**Comment by 47iscool** [comment]
Alright, thanks again.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/x2z9p31ifgnlvjp/droidsounde16647_26.apk?dl=0
see how it goes

**Comment by 47iscool** [comment]
Working great, thanks!
