### ISSUE TITLE
Folder scanning crashing dse

### ISSUE THREAD

**Issue by 47iscool** [droidmjt/Droidsound#255]
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.droidmjt.droidsounde.PlayerActivity$FolderWalker.getexternalSDPaths(PlayerActivity.java:1554)
	at com.droidmjt.droidsounde.PlayerActivity.processSDPaths(PlayerActivity.java:1454)
	at com.droidmjt.droidsounde.PlayerActivity.correctPath(PlayerActivity.java:1580)
	at com.droidmjt.droidsounde.PlayerActivity$FileBrowserDialog$2.onClick(PlayerActivity.java:5476)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:152)
	at android.app.ActivityThread.main(ActivityThread.java:5136)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
============================
Droidsound-E version: 39
Droidsound-E build: 16
Time: Thu Jan 14 10:54:00 EST 2016
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: zte/P821A17/demi:4.3/JLS36C/20140529.033010.24400:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 653533184
InternalSD path: /storage/sdcard0

**Comment by droidmjt** [comment]
how to reproduce this problem?

**Comment by droidmjt** [comment]
get the very latest version i just uploaded few hours ago

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/ladjir3tkyj9eok/droidsounde16647_28.apk?dl=0

**Comment by 47iscool** [comment]
Still chrashing, I simply select db file browser and try to mount it to my spc folder so will show name tags for snes and it crashes.

**Comment by 47iscool** [comment]
So for the typo, I meant crashing.

**Comment by droidmjt** [comment]
all right i will try to reproduce it

**Comment by droidmjt** [comment]
at com.droidmjt.droidsounde.PlayerActivity.correctPath(PlayerActivity.java:1580)

that line number means the call is coming from OnCreate() function in PlayerActivity.java, the only problem is that it was removed from there long time ago.

I can't reproduce your problem with the current version. I need the crashlog from the latest version.

**Comment by 47iscool** [comment]
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.droidmjt.droidsounde.PlayerActivity$FolderWalker.getexternalSDPaths(PlayerActivity.java:1504)
	at com.droidmjt.droidsounde.PlayerActivity.processSDPaths(PlayerActivity.java:1404)
	at com.droidmjt.droidsounde.PlayerActivity.correctPath(PlayerActivity.java:1530)
	at com.droidmjt.droidsounde.PlayerActivity$FileBrowserDialog$2.onClick(PlayerActivity.java:5490)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:152)
	at android.app.ActivityThread.main(ActivityThread.java:5136)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
============================
Droidsound-E version: 39
Droidsound-E build: 16
Time: Mon Jan 18 14:25:19 EST 2016
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: zte/P821A17/demi:4.3/JLS36C/20140529.033010.24400:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 1429434368
InternalSD path: /storage/sdcard0

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1lg2g6k7ffoegs0/droidsounde16647_29.apk?dl=0
I hope it works now.

**Comment by 47iscool** [comment]
Still crashing

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.droidmjt.droidsounde.PlayerActivity$FolderWalker.getexternalSDPaths(PlayerActivity.java:1500)
	at com.droidmjt.droidsounde.PlayerActivity.processSDPaths(PlayerActivity.java:1401)
	at com.droidmjt.droidsounde.PlayerActivity.correctPath(PlayerActivity.java:1527)
	at com.droidmjt.droidsounde.PlayerActivity$FileBrowserDialog$2.onClick(PlayerActivity.java:5489)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:152)
	at android.app.ActivityThread.main(ActivityThread.java:5136)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
============================
Droidsound-E version: 39
Droidsound-E build: 16
Time: Mon Jan 18 18:49:43 EST 2016
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: zte/P821A17/demi:4.3/JLS36C/20140529.033010.24400:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 1408860160
InternalSD path: /storage/sdcard0

**Comment by droidmjt** [comment]
what is your path that you try to mount?

**Comment by droidmjt** [comment]
nevermind, thats not the case

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/rh2ltpix52h7nsm/droidsounde16647_30.apk?dl=0

**Comment by droidmjt** [comment]
test the above binary

**Comment by droidmjt** [comment]
reopen this if the problem is still there

**Comment by 47iscool** [comment]
Still crashing,  I'm thinking it might be an spc issue, because mine are all extracted into subfolders.

**Comment by droidmjt** [comment]
send crashlog

**Comment by 47iscool** [comment]
Sorry I can't always reply back, I without the net at home and can only use it in areas with free WiFi or a friends house.

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/a0x8jjer1wv47mc/droidsounde16647_32.apk?dl=0

**Comment by 47iscool** [comment]
Still crashing

Whatever is causing it happened after you added support for the .ydsp extension.


Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.droidmjt.droidsounde.PlayerActivity$FolderWalker.getexternalSDPaths(PlayerActivity.java:1505)
	at com.droidmjt.droidsounde.PlayerActivity.processSDPaths(PlayerActivity.java:1403)
	at com.droidmjt.droidsounde.PlayerActivity.correctPath(PlayerActivity.java:1535)
	at com.droidmjt.droidsounde.PlayerActivity$FileBrowserDialog$2.onClick(PlayerActivity.java:5534)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:152)
	at android.app.ActivityThread.main(ActivityThread.java:5136)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
============================
Droidsound-E version: 39
Droidsound-E build: 30
Time: Sun Jan 24 14:05:00 EST 2016
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: zte/P821A17/demi:4.3/JLS36C/20140529.033010.24400:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 1209978880
InternalSD path: /storage/sdcard0

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/vcha266ebqakxki/droidsounde16647_33.apk?dl=0
try this

**Comment by 47iscool** [comment]
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.droidmjt.droidsounde.PlayerActivity$FolderWalker.getexternalSDPaths(PlayerActivity.java:1506)
	at com.droidmjt.droidsounde.PlayerActivity.processSDPaths(PlayerActivity.java:1404)
	at com.droidmjt.droidsounde.PlayerActivity.correctPath(PlayerActivity.java:1536)
	at com.droidmjt.droidsounde.PlayerActivity$FileBrowserDialog$2.onClick(PlayerActivity.java:5539)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:152)
	at android.app.ActivityThread.main(ActivityThread.java:5136)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
============================
Droidsound-E version: 39
Droidsound-E build: 30
Time: Sun Jan 24 19:50:55 EST 2016
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: zte/P821A17/demi:4.3/JLS36C/20140529.033010.24400:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 1348542464
InternalSD path: /storage/sdcard0

**Comment by droidmjt** [comment]
ah crap, i think i finally found the problem, lets see

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/k4aqzwyw7jzdb5d/droidsounde16647_35.apk?dl=0
try this

**Comment by 47iscool** [comment]
That did it, thanks.

If I may ask, what caused the issue?

**Comment by droidmjt** [comment]
java.util.ConcurrentModificationException
I was removing from an array that I iterated at the same time :(

**Comment by 47iscool** [comment]
Just wondering, thanks.
