### ISSUE TITLE
Bug/Crash: New Playqueue from Playlist, Add to Favorites from Playqueue

### ISSUE THREAD

**Issue by Level99OCR** [droidmjt/Droidsound#257]
Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.droidmjt.droidsounde.SongFile.getTitle()' on a null object reference
	at com.droidmjt.droidsounde.service.PlayerService$5.playList(PlayerService.java:1575)
	at com.droidmjt.droidsounde.PlayerServiceConnection.playList(PlayerServiceConnection.java:182)
	at com.droidmjt.droidsounde.PlayerActivity.onContextItemSelected(PlayerActivity.java:4981)
	at android.app.Activity.onMenuItemSelected(Activity.java:2949)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
	at com.android.internal.policy.impl.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:4700)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
	at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:167)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1082)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1147)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3058)
	at android.widget.AbsListView$3.run(AbsListView.java:3865)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5271)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
============================
Droidsound-E version: 39
Droidsound-E build: 16
Time: Mon Jan 18 09:17:29 EST 2016
CPU: armeabi-v7a
CPU: armeabi
Fingerprint: lge/w7_global_com/w7ds:5.0.2/LRX22G.A1423481010/15040202274a7:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 3589541888
InternalSD path: /storage/emulated/0

----------------------------

What I did to create the crashes:

Add folder to playlist, then try to make a new playqueue from that playlist.

On previous version, the above did not cause a crash. Once I created a new playqueue from a playlist, I switched active playlist to favorites, then when trying to add a file to favorites, the app would crash.

**Comment by droidmjt** [comment]
fixed

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/1lg2g6k7ffoegs0/droidsounde16647_29.apk?dl=0
