### ISSUE TITLE
Force closing in Android 6.0.1 (CM13 i9505)

### ISSUE THREAD

**Issue by zephemeros** [droidmjt/Droidsound#260]
Version 16647_09 - Force closes immediately upon opening the app
Versions 16647_22 and 27 - The app can be opened, but force closes immediately after attempting to play any sort of music file (NSF, SAP, XM etc). No sound is heard.

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.droidmjt.droidsounde.playlistview.PlayListAdapter.getView(PlayListAdapter.java:364)
	at android.widget.AbsListView.obtainView(AbsListView.java:2346)
	at android.widget.ListView.makeAndAddView(ListView.java:1876)
	at android.widget.ListView.fillDown(ListView.java:702)
	at android.widget.ListView.fillFromTop(ListView.java:763)
	at android.widget.ListView.layoutChildren(ListView.java:1671)
	at android.widget.AbsListView.onLayout(AbsListView.java:2148)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2934)
	at android.view.View.layout(View.java:16639)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5466)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
============================
Droidsound-E version: 39
Droidsound-E build: 34
Time: Sat Jan 23 20:13:44 PST 2016
CPU: armeabi-v7a
CPU: armeabi
Fingerprint: samsung/jfltexx/jflte:5.0.1/LRX22C/I9505XXUHOB7:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_GB
InternalSD free space: 519557120
InternalSD path: /storage/emulated/0

AND FOR BUILD 16:

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
	at com.droidmjt.droidsounde.plugins.GMEPlugin.load(GMEPlugin.java:434)
	at com.droidmjt.droidsounde.service.Player.startSong(Player.java:628)
	at com.droidmjt.droidsounde.service.Player.run(Player.java:1154)
	at java.lang.Thread.run(Thread.java:818)
============================
Droidsound-E version: 39
Droidsound-E build: 16
Time: Sat Jan 23 20:19:14 PST 2016
CPU: armeabi-v7a
CPU: armeabi
Fingerprint: samsung/jfltexx/jflte:5.0.1/LRX22C/I9505XXUHOB7:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_GB
InternalSD free space: 515399680
InternalSD path: /storage/emulated/0

**Comment by droidmjt** [comment]
>>Version 16647_09 - Force closes immediately upon opening the app. Versions 16647_22 and 27 - The app can be opened, but force closes immediately after attempting to play any sort of music file NSF, SAP, XM etc). No sound is heard.

did you have previously any earlier versions installed or was _09 the first version you ever installed?

Try the APK below and do fresh install. Remove the 'droidsound' and 'dsroot' folders and then install the APK below. If the crashing happens with the files, email them to me so i can check them.

https://www.dropbox.com/s/rh2ltpix52h7nsm/droidsounde16647_30.apk?dl=0

**Comment by zephemeros** [comment]
I'll do that now, will update with results in a moment
thanks for the quick response!

**Comment by zephemeros** [comment]
Alright, after doing as you said everything appears to be working well!

This is by far my favorite android app by the way, I've been using it for years now and I'm glad someone is still maintaining it and making additions. If I may suggest a possible feature, it'd be really cool to have a real-time pattern view for tracker modules like in XMPlay or Xmp.

**Comment by droidmjt** [comment]
Thanks for your support :) I'm glad it started working, one reason for a crash might be that you first installed version 27, then 09, 27 has newer DB structure than 09, thats why the very first crash. I should remove the old builds so users won't get confused :)

About your request, for that I would need to add a completely new view and it would be only for tracker music, unfortunately I have to say no for that. If you have other ideas, let me know, usually I'm able to add what users want.

**Comment by zephemeros** [comment]
I will, and thanks again for your help!
