### ISSUE TITLE
Now crashing when trying to add any kind of folder

### ISSUE THREAD

**Issue by 47iscool** [droidmjt/Droidsound#274]
Also crashes when scanning folders

Droidsound-E crashlog
=====================
STACKTRACE:
===========
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.droidmjt.droidsounde/com.droidmjt.droidsounde.PlayerActivity}: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.droidmjt.droidsounde.PlayerActivity$FileBrowserDialog: make sure class name exists, is public, and has an empty constructor that is public
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2214)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
	at android.app.ActivityThread.access$600(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:152)
	at android.app.ActivityThread.main(ActivityThread.java:5136)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.droidmjt.droidsounde.PlayerActivity$FileBrowserDialog: make sure class name exists, is public, and has an empty constructor that is public
	at android.app.Fragment.instantiate(Fragment.java:596)
	at android.app.FragmentState.instantiate(Fragment.java:97)
	at android.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1747)
	at android.app.Activity.onCreate(Activity.java:893)
	at android.support.v4.app.BaseFragmentActivityDonut.onCreate(BaseFragmentActivityDonut.java:39)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:278)
	at com.droidmjt.droidsounde.PlayerActivity.onCreate(PlayerActivity.java:1583)
	at android.app.Activity.performCreate(Activity.java:5133)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
	... 11 more
Caused by: java.lang.InstantiationException: can't instantiate class com.droidmjt.droidsounde.PlayerActivity$FileBrowserDialog; no empty constructor
	at java.lang.Class.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1130)
	at android.app.Fragment.instantiate(Fragment.java:585)
	... 20 more
============================
Droidsound-E version: 39
Droidsound-E build: 31
Time: Mon Mar 14 16:55:05 EDT 2016
CPU: armeabi-v7a
CPU2: armeabi
Fingerprint: zte/P821A17/demi:4.3/JLS36C/20140529.033010.24400:user/release-keys
CPUFeatures : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
Lang: English
Locale: en_US
InternalSD free space: 2120060928
InternalSD path: /storage/sdcard0

**Comment by droidmjt** [comment]
what is build number?

**Comment by droidmjt** [comment]
what do you mean by any kind of folder? i think there are just one kind of folders :)

**Comment by droidmjt** [comment]
at least don't use the build _43, its faulty

**Comment by 47iscool** [comment]
Could I have a link to a more stable build?

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/rq5nq0xbeax0lvc/droidsounde16647_44.apk?dl=0
