### ISSUE TITLE
Crashes when opening file from external file manager

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#399]
This happens regardless of whether Xposed is installed or not.

Stack trace:
```
java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:438)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.droidmjt.droidsounde.PlayerActivity.onNewIntent(PlayerActivity.java:1029)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1245)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1257)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2804)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2816)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2825)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

I discovered that using Xposed module "Scoop" to automatically capture stack traces is extremely helpful, and would recommend it for everyone.

**Comment by droidmjt** [comment]
does it happen with any file format?

**Comment by jimbo1qaz** [comment]
I think it's independent of format. It has happened with zip, opus, spc, etc.

**Comment by droidmjt** [comment]
Found the bug, I'll check it.

**Comment by droidmjt** [comment]
try this: https://www.dropbox.com/s/8ygrvtj4ucdo6ru/droidsounde167_73.apk?dl=1

**Comment by jimbo1qaz** [comment]
Bug still occurs from https://play.google.com/store/apps/details?id=com.simplemobiletools.filemanager&hl=en

Does not occur when opening from https://play.google.com/store/apps/details?id=com.amaze.filemanager&hl=en

I'm not sure if Amaze was broken before.

**Comment by droidmjt** [comment]
I tested simplemobile filemanager with SGS8 and works normally. I can try with few other devices. Please send the crash log in the mean time.

**Comment by jimbo1qaz** [comment]
https://gist.github.com/jimbo1qaz/96332da0c2ecf4daf5eeffb4c5b37caf
One factor is I have the Music folder in both a music library, and file explorer. Is that relevant?

I rebooted. It crashed once and is no longer crashing from any file manager.

Observation: I close DSE (X button, or swipe from recents) and open a file from a file manager. Why does it popup blank screen, DSE GUI for half a second, another blank screen, and finally DSE? If I close and open DSE, I only get a blank screen once.

**Comment by jimbo1qaz** [comment]
Still happening on 167_94.
```
java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:438)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
	at com.droidmjt.droidsounde.PlayerActivity.onNewIntent(PlayerActivity.java:936)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1245)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1257)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2804)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2816)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2825)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by droidmjt** [comment]
I was able to reproduce this problem and fixed it, unfortunately I found another bug what is a bit annoying, once I have fixed it I upload a new binary.

**Comment by jimbo1qaz** [comment]
the first time i opened from for manager, the song paused after half a second. All subsequent files i open (whether the same or different file) work fine.

**Comment by droidmjt** [comment]
yeah weird, It worked fine on emulator, I should test more with real devices

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/2b4jj9qhxl432nq/droidsounde167_96.apk?dl=1
try this

**Comment by jimbo1qaz** [comment]
I'm going to report this on a different issue, im getting state erors and sqlite crashes which may be linked to the pause-on-start glitch. (when trying to trigger pause on start, it crashed with android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
	at com.droidmjt.droidsounde.database.SongDatabase.setRescan(SongDatabase.java:311)
	at com.droidmjt.droidsounde.database.SongDatabase.doScan(SongDatabase.java:1542)
	at com.droidmjt.droidsounde.database.SongDatabase.access$300(SongDatabase.java:108)
	at com.droidmjt.droidsounde.database.SongDatabase$MyHandler.handleMessage(SongDatabase.java:460)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at com.droidmjt.droidsounde.database.SongDatabase.run(SongDatabase.java:515)
	at java.lang.Thread.run(Thread.java:761)

**Comment by droidmjt** [comment]
If you use build _96 with simplemobile filemanager to launch an .NSF file from /sdcard/Music/, do you still get the usual errors?
