### ISSUE TITLE
Huge Playlist Crashing The App 

### ISSUE THREAD

**Issue by Ozaleto** [droidmjt/Droidsound#400]
Hey there, I have a playlist with 12,092 tracks (so I can shuffle through a ton of music in different folders) and every time I try to play a song through the playlist the app closes and says it needs to be restarted, even though the song is playing perfectly fine in the background until I restart.

I believe this is only an issue with very huge playlists, as I was still able to play tracks perfectly from a playlist that has 4,000 tracks.

I'm not too sure what other info I could give, but it would be appreciated if this could be checked on.

Thanks!

**Comment by droidmjt** [comment]
logcat log of the crash please, otherwise i cannot fix it

**Comment by Ozaleto** [comment]
I won't be able to root my phone for now since I don't have access to a computer, so I will close this case and open a new one once I am able to root my phone and get the log.

**Comment by droidmjt** [comment]
you don't need to root anything, you get the log by using your PC

**Comment by droidmjt** [comment]
The maximum amount of entries you can have in one playlist is 11023 songs, its the Android limitation of CursorWindowCapacity. I suggest you reorganize your playlists :)

**Comment by Ozaleto** [comment]
Ah, alright. Thanks!

**Comment by Ozaleto** [comment]
Hello, I was able to successfully get it under 11023 tracks (currently 10982) and it still crashes. I will reopen as soon as I am able to get a log.

**Comment by Ozaleto** [comment]
Hey, so I found the crash log for the recent one when I try to open a playlist that's under 11023:

```java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1052)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:677)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:403)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:905)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:151)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:123)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:236)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
	at com.droidmjt.droidsounde.playlistview.PlayListAdapter.getFiles(PlayListAdapter.java:697)
	at com.droidmjt.droidsounde.playlistview.PlayListAdapter.setHilightedFile(PlayListAdapter.java:788)
	at com.droidmjt.droidsounde.playlistview.PlayListView.setHilighted(PlayListView.java:132)
	at com.droidmjt.droidsounde.PlayerActivity.update(PlayerActivity.java:4286)
	at com.droidmjt.droidsounde.PlayerActivity$ValueChangeHandler.handleMessage(PlayerActivity.java:4058)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6688)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)```

**Comment by droidmjt** [comment]
The error looks familiar, try reducing the playlist size. Playlists of that size are just pure nonsense. I'm curious, why do you have so many items in one playlist?

**Comment by Ozaleto** [comment]
It's pretty much every Sega Genesis OST. I wanted it as one playlist so I can shuffle through all of the songs from all the different folders, since shuffling songs that are from different folders isn't possible, only from one folder.

It was possible on this one iOS app named NESMusic but in the end, it really isn't that necessary now that I look over it.

**Comment by droidmjt** [comment]
I think there is another way to achieve what you are doing there. Create DB browser of your songs, for example if you have them in /sdcard/Music/Sega, select that folder as mountpoint for DB Browser, after scanning, you can queue the whole directory.

**Comment by Ozaleto** [comment]
That worked, thank you!

**Comment by droidmjt** [comment]
Excellent
