### ISSUE TITLE
Crash on rescanning db

### ISSUE THREAD

**Issue by Xkeeper0** [droidmjt/Droidsound#425]
I have a folder structure like this:
/Music/
/Music/<various folders with ogg, mp3>
/Music/Game Music/<N64, NSF, SPC>/

Upon opening the app, the program tries to scan this directory for media and crashes after a few seconds. Specifically, it is crashing in the SPC section (but it does not do any others first)

This same set of files was used in an older Droidsound-e version, at least a few months ago, without issue. I do not know the old version right now.

This is a new installation of Droidsound.

Here is the output from logcat. This took some teeth pulling to get, but hopefully it helps.
https://pastebin.com/raw/yMHJyAwQ

Here is the end of the log file:

```
07-12 00:58:39.053 19693 19755 D Droidsound-E: SongDatabase: Adding 0 paths
07-12 00:58:39.053 19693 19755 D Droidsound-E: SongDatabase: ARCHIVE TRANSACTION SUCCESSFUL
07-12 00:58:39.053 19693 19755 D Droidsound-E: SongDatabase: PATH /storage/emulated/0/Music/Game Music/SPC/Knights of the Round [kotr].rsn 0
07-12 00:58:39.054 19693 19755 D Droidsound-E: SongDatabase: Scanning /storage/emulated/0/Music/Game Music/SPC/Knights of the Round [kotr].rsn
07-12 00:58:39.094 19693 19755 D Droidsound-E: SongDatabase: OPEN
07-12 00:58:39.097 19693 19755 D Droidsound-E: SongDatabase: ENUM
07-12 00:58:39.099 19693 19755 D Droidsound-E: SongDatabase: ENUMERATING
07-12 00:58:39.099 19693 19755 D Droidsound-E: SongDatabase: Could not identify 'info.txt'
--------- beginning of crash
07-12 00:58:39.102 19693 19755 E AndroidRuntime: FATAL EXCEPTION: Thread-4
07-12 00:58:39.102 19693 19755 E AndroidRuntime: Process: com.droidmjt.droidsounde, PID: 19693
07-12 00:58:39.102 19693 19755 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=66092; index=66092
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.FileIdentifier.parse_SPC_xid6_data(FileIdentifier.java:447)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.FileIdentifier.identify(FileIdentifier.java:1016)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.database.SongDatabase.scanZip(SongDatabase.java:775)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:1198)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:1308)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:1308)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.database.SongDatabase.scanFiles(SongDatabase.java:1330)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.database.SongDatabase.doScan(SongDatabase.java:1663)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.database.SongDatabase.access$300(SongDatabase.java:108)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.database.SongDatabase$MyHandler.handleMessage(SongDatabase.java:460)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at com.droidmjt.droidsounde.database.SongDatabase.run(SongDatabase.java:515)
07-12 00:58:39.102 19693 19755 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

...also, because the app immediately tries to rescan on load (because I turned that option on, oops) it is impossible to use this or reset the preferences, as it immediately begins rescanning as soon as I open it. :/ Without that I could at least load the files directly...

**Comment by droidmjt** [comment]
thanks for the log, it helps, I'll check this as soon as possible

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/nfuzn2clns9u0i6/droidsounde167_97.apk?dl=1
try this

**Comment by Xkeeper0** [comment]
Finished scanning the entire tree without issue, looks good to me. Thanks.

**Comment by droidmjt** [comment]
great
